routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware'=>'auth'], function(){
    Route::get('/', 'MainController@getCustomerPage')->name('customers');
    Route::get('/Users', 'MainController@getUserPage')->name('users');
    Route::get('CustomerPoints/{id}', 'CustomerController@claimOrRedeemPoints')->name('customer_points');
    Route::put('ClaimOrRedeem/{id}', 'CustomerController@putClaimOrRedeemPoints')->name('claim_redeem');
    Route::post('/AddUser', 'Auth\RegisterController@create')->name('add_users');
    Route::resource('customer', 'CustomerController', ['as' => 'customers']);
    Route::resource('user', 'UserController', ['as' => 'users']);
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $fillable = [
        'customer_name',
        'branch_name',
        'points'
    ];

    protected $table = 'customers';
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Customer;
use App\Modules\Customer as Service;


class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Customer::create($request->all());
        return Service::getPage();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return Service::getPage(true, Customer::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Customer::where('id', $id)->update([
            'customer_name' => $request->get('customer_name'),
            'branch_name' => $request->get('branch_name')
        ]);
        return Service::getPage();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return Customer::destroy($id);
    }

    public function claimOrRedeemPoints($id)
    {
        return Service::toPageData( $id, true );
    }

    public function putClaimOrRedeemPoints( Request $request, $id )
    {
        $customer = Customer::find($id);

        if( $request->get('type') == 'claim' ){
            $customer->points += (float) $request->get('points');
        } else {
            $customer->points -= (float) $request->get('points');
        }

        $customer->save();
        
        return Service::getPage(true, Customer::find($id));
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Modules\Customer;
use App\Modules\User;

class MainController extends Controller
{
    public function getCustomerPage()
    {
        return Customer::getPage(true);
    }

    public function getUserPage()
    {
        return User::getPage(true);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Modules\User as Service;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
        return Service::getPage();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return Service::getPage(true, User::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        User::where('id', $id)->update([
            'name' => $request->get('name'),
            'email' => $request->get('email')
        ]);
        return Service::getPage();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return User::destroy($id);
    }
}

resources/views/content.blade.php
<div class="content-wrapper py-3">
    <div class="container-fluid">
        @include($page)
    </div>
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'TGP Points') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'TGP Points') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/navigation.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="#">TGP Points</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav">
          <li class="nav-item {{ Route::is('customers') ? 'active' : '' }}" data-toggle="tooltip" data-placement="right" title="" data-original-title="Charts">
            <a class="nav-link" href="{{route('customers')}}">
              <i class="fa fa-fw fa-users"></i>
              <span class="nav-link-text">
                Customers</span>
            </a>
          </li>
          <li class="nav-item {{ Route::is('users') ? 'active' : '' }}" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
            <a class="nav-link" href="{{route('users')}}">
              <i class="fa fa-fw fa-user"></i>
              <span class="nav-link-text">
                Users</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

resources/views/pages/customer_points.blade.php
<div class="container">
<h3>Customer Points {{$data->customer_name}}</h3>
  <form method="POST" action="{{route('claim_redeem', $data->id)}}">
    <div class="form-group row">
      <label class="col-sm-4 control-label">Current Points</label>
      <div class="col-sm-10">
        <input type="text" disabled class="form-control" placeholder="Points" value="{{$data->points}}">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-4 control-label">Points</label>
      <div class="col-sm-10">
        <input type="text" name="points" class="form-control" placeholder="Points" >
      </div>
    </div>
    <fieldset class="form-group row">
      <div class="col-sm-10">
        <div class="form-check">
          <label class="form-check-label">
             <input type="radio" name="type" placeholder="Points" value="claim" checked>
             Claim
          </label>
        </div>
        <div class="form-check">
          <label class="form-check-label">
             <input type="radio" name="type" placeholder="Points" value="redeem">
             Redeem
          </label>
        </div>
    </fieldset>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="PUT">
        <button type="submit" class="btn btn-primary">Claim / Redeem</button>
      </div>
    </div>
  </form>
</div>

resources/views/pages/customers.blade.php
@if(!\Route::is('customers.customer.edit'))
<h3>Customers</h3>
<form class="form-inline" method="POST" action="{{route('customers.customer.store')}}">
  <div class="form-group col-md-3">
    <label class="col-sm-4 control-label">Full name</label>
    <div class="col-sm-8">
    <input type="text" name="customer_name" class="form-control"placeholder="Full name">
    </div>
  </div>
  <div class="form-group col-md-3">
    <label class="col-sm-3 control-label">Branch</label>
    <div class="col-sm-9">
        <select name="branch_name" id="" class="form-control">
            <option>Marilao</option>
            <option>Quatro Kanto</option>
            <option>Taytay</option>
        </select>
    </div>
  </div>
  <div class="form-group col-md-3">
    <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
    <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>
@else
<h3>Customer {{$data->customer_name}}</h3>
<form class="form-inline" method="POST" action="{{route('customers.customer.update', $data->id)}}">
  <div class="form-group col-md-3 ">
    <label class="col-sm-4 control-label">Full name</label>
    <div class="col-sm-8">
    <input type="text" name="customer_name" class="form-control"placeholder="Full name" value="{{$data->customer_name}}">
    </div>
  </div>
  <div class="form-group col-md-3">
    <label class="col-sm-3 control-label">Branch</label>
    <div class="col-sm-9">
        <select name="branch_name" id="" class="form-control">
            <option @if( $data->branch_name == 'Marilao')selected=""@endif>Marilao</option>
            <option @if( $data->branch_name == 'Quatro')selected=""@endif>Quatro Kanto</option>
            <option @if( $data->branch_name == 'Taytay')selected=""@endif>Taytay</option>
        </select>
    </div>
  </div>
  <div class="form-group col-md-3">
    <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
    <input type="hidden" name="_method" value="PUT">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>
@endif

<table class="table col-md-12">
  <thead> 
    <tr> 
      <th>Name</th> 
      <th>Branch Name</th> 
      <th>Points</th> 
      <th>Actions</th> 
    </tr> 
  </thead>
  <tbody>
    @foreach( $customers as $customer )
      <tr>
        <td>{{$customer->customer_name}}</td>
        <td>{{$customer->branch_name}}</td>
        <td>{{$customer->points}}</td>
        <td>
          @if(!\Route::is('customers.customer.edit'))<a role="button" href="{{route('customers.customer.destroy', $customer->id)}}" data-method="DELETE" class="postback"><span class="fa fa-trash text-danger"></span></a>&nbsp;&nbsp;&nbsp;@endif
          <a role="button" href="{{route('customers.customer.edit', $customer->id)}}"><span class="fa fa-edit"></span></a> &nbsp;&nbsp;&nbsp
          <a role="button" class="btn btn-info btn-sm" href="{{route('customer_points', $customer->id)}}">Claim / Redeem Points</a> 
        </td>
      </tr>  
    @endforeach
  </tbody> 
</table>

resources/views/pages/users.blade.php
@if(!\Route::is('users.user.edit'))
<h3>Users</h3>
<form class="form-inline" action="{{route('users.user.store')}}" method="POST">
  <div class="form-group col-md-2">
    <div class="col-sm-8">
    <input type="text" name="name" class="form-control"placeholder="Full name">
    </div>
  </div>
  <div class="form-group col-md-2">
    <div class="col-sm-10">
    <input type="email" name="email" class="form-control" placeholder="Email">
    </div>
  </div>
  <div class="form-group col-md-2">
    <div class="col-sm-9">
      <input type="password" name="password" class="form-control" placeholder="Password">
    </div>
  </div>
  <div class="form-group col-md-2">
    <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
    <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>
@else
<h3>User {{$data->name}}</h3>
<form class="form-inline" method="POST" action="{{route('users.user.update', $data->id)}}">
  <div class="form-group col-md-3">
    <div class="col-sm-8">
    <input type="text" name="name" class="form-control"placeholder="Full name" value="{{$data->name}}">
    </div>
  </div>
  <div class="form-group col-md-3">
    <div class="col-sm-10">
    <input type="email" name="email" class="form-control" placeholder="Email" value="{{$data->email}}">
    </div>
  </div>
  <div class="form-group col-md-3">
    <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
    <input type="hidden" name="_method" value="PUT">
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
</form>
@endif


<table class="table col-md-12">
  <thead> 
    <tr> 
      <th>Name</th> 
      <th>Email</th> 
      <th>Actions</th> 
    </tr> 
  </thead>
  <tbody>
    @foreach( $users as $user )
      <tr>
        <td>{{$user->name}}</td>
        <td>{{$user->email}}</td>
        <td>
          @if(!\Route::is('users.user.edit'))<a role="button" href="{{route('users.user.destroy', $user->id)}}" data-method="DELETE" class="postback"><span class="fa fa-trash text-danger"></span></a>&nbsp;&nbsp;&nbsp;@endif
          <a role="button" href="{{route('users.user.edit', $user->id)}}"><span class="fa fa-edit"></span></a> 
        </td>
      </tr>  
    @endforeach
  </tbody> 
</table>

resources/views/tgp.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'TGP Points') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    {{ Html::style('vendor/font-awesome/css/font-awesome.min.css') }}
    {{ Html::style('css/custom.css') }}
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'TGP Points') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li><a href="{{route('users')}}">Users</a></li>
                            <li><a href="{{route('customers')}}">Customers</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        <div class="col-md-10 col-md-offset-1">
            @include('content')
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
(() => {
$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('input[name="_token"]').attr('value')
    }
});
$(document).on('click', 'a.postback', function(e) {
    e.preventDefault(); // does not go through with the link.

    var $this = $(this);
    console.log($this.data('method'));
    $.ajax({
        type: $this.data('method'),
        url: $this.attr('href'),
        headers: {
            'X-CSRF-TOKEN': $('meta[name="token"]').attr('content')
        },
        data : {
            'token' : $('meta[name="token"]').attr('content')
        }
    }).done(function (data) {
        location.reload();
    });
});
})();
</script>
</body>
</html>